<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="AnchorFree-VM" ignored="8" name="DemoAutomation" tests="4" failures="1" timestamp="30 Jan 2021 17:23:15 GMT" time="364.889" errors="0">
  <testcase name="createCampaign" time="66.795" classname="com.client.xenon.tests.AccountToOpportunityFlow"/>
  <testcase name="createLeadFromCampaign" time="31.909" classname="com.client.xenon.tests.AccountToOpportunityFlow"/>
  <testcase name="convertLeadtoOpportunity" time="211.993" classname="com.client.xenon.tests.AccountToOpportunityFlow">
    <failure type="java.lang.AssertionError" message="Verification error">
      <![CDATA[java.lang.AssertionError: Verification error
	at org.testng.Assert.fail(Assert.java:94)
	at com.client.xenon.operations.PageObjects.convertLeadToOpportunity(PageObjects.java:351)
	at com.client.xenon.tests.AccountToOpportunityFlow.convertLeadtoOpportunity(AccountToOpportunityFlow.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at com.xenon.core.framework.Xenon.excute(Xenon.java:173)
	at com.client.xenon.framework.DemoAutomation.main(DemoAutomation.java:15)
]]>
    </failure>
  </testcase> <!-- convertLeadtoOpportunity -->
  <testcase name="verificationCheck" time="51.693" classname="com.client.xenon.tests.AccountToOpportunityFlow"/>
  <testcase name="createInvoice" time="0.0" classname="com.client.xenon.tests.P2PTestCases">
    <ignored/>
  </testcase> <!-- createInvoice -->
  <testcase name="createAccounting" time="0.0" classname="com.client.xenon.tests.P2PTestCases">
    <ignored/>
  </testcase> <!-- createAccounting -->
  <testcase name="validateAccountingNonPOInvoice" time="0.0" classname="com.client.xenon.tests.P2PTestCases">
    <ignored/>
  </testcase> <!-- validateAccountingNonPOInvoice -->
  <testcase name="createNoncatalogRequisition" time="0.0" classname="com.client.xenon.tests.P2PTestCases">
    <ignored/>
  </testcase> <!-- createNoncatalogRequisition -->
  <testcase name="createBatchPaymentForInvoice" time="0.0" classname="com.client.xenon.tests.P2PTestCases">
    <ignored/>
  </testcase> <!-- createBatchPaymentForInvoice -->
  <testcase name="receiveItems" time="0.0" classname="com.client.xenon.tests.P2PTestCases">
    <ignored/>
  </testcase> <!-- receiveItems -->
  <testcase name="processRequisition" time="0.0" classname="com.client.xenon.tests.P2PTestCases">
    <ignored/>
  </testcase> <!-- processRequisition -->
  <testcase name="requestPRApproval" time="0.0" classname="com.client.xenon.tests.P2PTestCases">
    <ignored/>
  </testcase> <!-- requestPRApproval -->
</testsuite> <!-- DemoAutomation -->
