<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.client.xenon.tests.P2PTestCases" tests="1" time="169.895" ignored="7" failures="1" timestamp="05 Nov 2019 09:35:49 GMT" skipped="0" hostname="PNL-1H883H2" errors="0">
  <testcase name="createNoncatalogRequisition" time="169.895" classname="com.client.xenon.tests.P2PTestCases">
    <failure type="java.lang.AssertionError" message="Element is not found.">
      <![CDATA[java.lang.AssertionError: Element is not found.
	at org.testng.Assert.fail(Assert.java:94)
	at com.xenon.utility.selenium.Elements.clickMethod(Elements.java:244)
	at com.xenon.utility.selenium.Elements.click(Elements.java:233)
	at com.client.xenon.operations.P2POperations.createNoncatalogRequisition(P2POperations.java:101)
	at com.client.xenon.tests.P2PTestCases.createNoncatalogRequisition(P2PTestCases.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at com.xenon.core.framework.Xenon.excute(Xenon.java:154)
	at com.client.xenon.framework.DemoAutomation.main(DemoAutomation.java:15)
]]>
    </failure>
  </testcase> <!-- createNoncatalogRequisition -->
  <testcase name="createInvoice" classname="com.client.xenon.tests.P2PTestCases">
    <skipped/>
  </testcase> <!-- createInvoice -->
  <testcase name="createAccounting" classname="com.client.xenon.tests.P2PTestCases">
    <skipped/>
  </testcase> <!-- createAccounting -->
  <testcase name="validateAccountingNonPOInvoice" classname="com.client.xenon.tests.P2PTestCases">
    <skipped/>
  </testcase> <!-- validateAccountingNonPOInvoice -->
  <testcase name="createBatchPaymentForInvoice" classname="com.client.xenon.tests.P2PTestCases">
    <skipped/>
  </testcase> <!-- createBatchPaymentForInvoice -->
  <testcase name="receiveItems" classname="com.client.xenon.tests.P2PTestCases">
    <skipped/>
  </testcase> <!-- receiveItems -->
  <testcase name="processRequisition" classname="com.client.xenon.tests.P2PTestCases">
    <skipped/>
  </testcase> <!-- processRequisition -->
  <testcase name="requestPRApproval" classname="com.client.xenon.tests.P2PTestCases">
    <skipped/>
  </testcase> <!-- requestPRApproval -->
</testsuite> <!-- com.client.xenon.tests.P2PTestCases -->
